/Users/owencotter/spontaneous-trip-generator/spontaneous-trip-generator/venv/bin/python3: can't open file '/Users/owencotter/spontaneous-trip-generator/spontaneous-trip-generator/backend/manage.py': [Errno 2] No such file or directory
